### ISSUE TITLE
Parser cannot deal truncate statement

### ISSUE THREAD

**Issue by sinri** [phpmyadmin/sql-parser#221]
(1) First, cannot parse common truncate statement.

```php
$query="truncate a";
$parser = new Parser($query,true);
```

would throw 

```
PHP Fatal error:  Uncaught PhpMyAdmin\SqlParser\Exceptions\ParserException: Unexpected token. in /Users/sinri/code/phpstorm/sql-parser/src/Parser.php:617
Stack trace:
#0 /Users/sinri/code/phpstorm/sql-parser/src/Statement.php(247): PhpMyAdmin\SqlParser\Parser->error('Unexpected toke...', Object(PhpMyAdmin\SqlParser\Token))
#1 /Users/sinri/code/phpstorm/sql-parser/src/Statement.php(90): PhpMyAdmin\SqlParser\Statement->parse(Object(PhpMyAdmin\SqlParser\Parser), Object(PhpMyAdmin\SqlParser\TokensList))
#2 /Users/sinri/code/phpstorm/sql-parser/src/Parser.php(516): PhpMyAdmin\SqlParser\Statement->__construct(Object(PhpMyAdmin\SqlParser\Parser), Object(PhpMyAdmin\SqlParser\TokensList))
#3 /Users/sinri/code/phpstorm/sql-parser/src/Parser.php(381): PhpMyAdmin\SqlParser\Parser->parse()
#4 /Users/sinri/code/phpstorm/sql-parser/doc/1.php(14): PhpMyAdmin\SqlParser\Parser->__construct('truncate a', true)
#5 {main}
  thrown in /Users/sinri/code/phpstorm/sql-parser/src/Parser.php on line 617
```

Only `TRUNCATE table x.y` is accepted.

(2) Cannot build an existed TruncateStatement.

Which would return empty string.

Version Commit 28427543

**Comment by sinri** [comment]
Tried to parse two kinds of keyword in one query string.

`truncate table `a`.`b`;select 1`

got

```
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseKeyword MET TOKEN {"token":"truncate","value":"truncate","keyword":"TRUNCATE","type":1,"flags":33,"position":null}
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseWhitespace MET TOKEN {"token":" ","value":" ","keyword":null,"type":3,"flags":0,"position":null}
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseKeyword MET TOKEN {"token":"table","value":"TABLE","keyword":"TABLE","type":1,"flags":3,"position":null}
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseWhitespace MET TOKEN {"token":" ","value":" ","keyword":null,"type":3,"flags":0,"position":null}
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseSymbol MET TOKEN {"token":"`a`","value":"a","keyword":null,"type":8,"flags":2,"position":null}
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseOperator MET TOKEN {"token":".","value":".","keyword":null,"type":2,"flags":16,"position":null}
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseSymbol MET TOKEN {"token":"`b`","value":"b","keyword":null,"type":8,"flags":2,"position":null}
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseDelimiter MET TOKEN {"token":";","value":";","keyword":null,"type":9,"flags":0,"position":null}
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseKeyword MET TOKEN {"token":"select","value":"SELECT","keyword":"SELECT","type":1,"flags":3,"position":null}
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseWhitespace MET TOKEN {"token":" ","value":" ","keyword":null,"type":3,"flags":0,"position":null}
PhpMyAdmin\SqlParser\Lexer::lex@230 METHOD: parseNumber MET TOKEN {"token":"1","value":1,"keyword":null,"type":6,"flags":0,"position":null}
```

Note the value field of SELECT and TRUNCATE, they are obviously different.
